# 4.5 Linear Algebra

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
x @ np.ones(3) # @ for matrix multiplication

array([ 6., 15.])

In [9]:
from numpy.linalg import inv, qr

In [10]:
X = np.random.randn(5, 5)

In [11]:
mat = X.T.dot(X)

In [12]:
inv(mat)

array([[ 0.39186227,  0.22835423, -0.09646142, -0.55367338, -0.17865166],
       [ 0.22835423, 10.27204385,  6.30902281, -1.53904052,  0.67665296],
       [-0.09646142,  6.30902281,  4.66666313, -1.0160171 ,  0.35609172],
       [-0.55367338, -1.53904052, -1.0160171 ,  1.62087645,  0.33594114],
       [-0.17865166,  0.67665296,  0.35609172,  0.33594114,  0.4652479 ]])

In [13]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.99840144e-15, -3.33066907e-16,
         0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  8.32667268e-16,
        -1.66533454e-16,  2.22044605e-16],
       [-8.32667268e-17,  3.21964677e-15,  1.00000000e+00,
        -1.11022302e-16,  1.66533454e-16],
       [-1.38777878e-17, -1.55431223e-15, -2.77555756e-17,
         1.00000000e+00,  5.55111512e-17],
       [-1.11022302e-16, -8.88178420e-16, -1.11022302e-15,
         2.22044605e-16,  1.00000000e+00]])

In [14]:
q, r = qr(mat)

In [15]:
r

array([[-11.56472809,   2.54691512,  -4.48630475,  -4.10946389,
         -2.03098407],
       [  0.        ,  -1.11310572,   1.27976173,  -0.88586681,
          2.16211876],
       [  0.        ,   0.        ,  -0.59738079,  -1.20631045,
          2.87595597],
       [  0.        ,   0.        ,   0.        ,  -0.4061355 ,
         -0.2591079 ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.02820547]])

---