# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [1]:
import numpy as np

A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.

In [2]:
arr = np.arange(10)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
x = np.random.randn(8)
y = np.random.randn(8)

In [6]:
np.maximum(x, y)

array([-0.4845429 ,  0.7178205 ,  2.22559233, -0.75505708,  0.95723901,
        0.99264136,  0.94463594,  0.99074461])

In [7]:
arr = np.random.randn(7) * 5

In [8]:
arr

array([ 1.83001838, -4.88530851,  1.50607622, -4.99298933, -2.74635456,
        2.6848411 ,  0.90668287])

In [9]:
remainder, whole_part = np.modf(arr)

In [10]:
remainder

array([ 0.83001838, -0.88530851,  0.50607622, -0.99298933, -0.74635456,
        0.6848411 ,  0.90668287])

In [11]:
whole_part

array([ 1., -4.,  1., -4., -2.,  2.,  0.])

---