# 5.1 Introduction to pandas Data Structures

Data structures and data manipulation tools.

In [16]:
import numpy as np
import pandas as pd

pandas main data structures: Series and DataFrame.

## Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) and an associated array of data labels, called index.

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2[obj2 < 0]

a   -5
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2) # using ufunc

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Idea: Series as a fixed-length, ordered dict, as it is a mapping of index values to data values.

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [21]:
6 in obj2 # only checking for index, not value

False

In [22]:
-5 in obj2

False

In [23]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
obj3 = pd.Series(sdata)

In [25]:
obj3 # the keys of dictionary will become Series index

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [27]:
obj4 = pd.Series(sdata, index=states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
pd.Series(sdata, index=tuple(states)) # the specified index can be a tuple

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.Series(sdata, index=set(states))

Ohio          35000.0
Texas         71000.0
California        NaN
Oregon        16000.0
dtype: float64

In [31]:
pd.Series(range(4), index=tuple(states))

California    0
Ohio          1
Oregon        2
Texas         3
dtype: int64

In [33]:
pd.Series(range(4), index=set(states)) 
# becareful of this thing, because set will not return in any specified order

Ohio          0
Texas         1
California    2
Oregon        3
dtype: int64

In [34]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [36]:
obj4.keys() 
# instance method keys will return the same thing as index

Index(['California', 'Ohio', 'Oregon', 'Texas'], dtype='object')

In [39]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [40]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [41]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [42]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series will automatically align the index-value when performing operations:

In [43]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [44]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [45]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [46]:
obj4.name = 'population'

In [47]:
obj4.index.name = 'state'

In [48]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [49]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [50]:
# changing index through assignment
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [51]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

----

## DataFrame

A DataFrame represents a rectangular table of data and contains an ordered collection
of columns, each of which can be a different value type (numeric, string,
boolean, etc.).

In [52]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [53]:
frame = pd.DataFrame(data)

In [54]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [55]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [56]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [57]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

In [58]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [61]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [62]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [64]:
frame2.dtypes

year       int64
state     object
pop      float64
debt      object
dtype: object

In [65]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [66]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Note that the returned Series have the same index as the DataFrame, and their name
attribute has been appropriately set.

In [67]:
frame2.loc['three'] # accessing rows

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [68]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [70]:
frame2.loc[:, ['state', 'debt']]

state debt
one      Ohio  NaN
two      Ohio  NaN
three    Ohio  NaN
four   Nevada  NaN
five   Nevada  NaN
six    Nevada  NaN

In [71]:
frame2['debt'] = 16.5

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [73]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [74]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [75]:
frame2['debt'] = val

In [76]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

Assigning a column that doesn’t exist will create a new column. The del keyword will
delete columns as with a dict.

In [78]:
frame2['eastern'] = (frame2.state == 'Ohio')

In [79]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [80]:
del frame2['eastern']
# deleting a column

In [81]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [82]:
del frame2.loc['four', 'debt'] # cannot delete individual value with del

AttributeError: __delitem__

In [84]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
# outer dict keys will be column labels, inner dict keys will be index label

In [85]:
frame3 = pd.DataFrame(pop)

In [86]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [87]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [88]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [89]:
pdata = {'Ohio': frame3['Ohio'][:-1], 
         'Nevada': frame3['Nevada'][:2]}

In [90]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [91]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [92]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [93]:
frame3.values
# return ndarray

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [94]:
frame2.values
# the dtype will be object to accomodate the differsity of data types

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

---

## Index Objects

pandas’s Index objects are responsible for holding the axis labels and other metadata
(like the axis name or names).

In [96]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [97]:
index = obj.index

In [98]:
index

Index(['a', 'b', 'c'], dtype='object')

Index is a immutable object

In [99]:
labels = pd.Index(np.arange(3))

In [100]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [101]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [102]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [103]:
obj2.index is labels

True

In addition to being array-like, an Index also behaves like a fixed-size set:

In [104]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [106]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [107]:
'Ohio' in frame3.columns

True

In [109]:
2000 in frame3.index

True

Index can contain duplicate labels

In [110]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [111]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [113]:
dup_labels.isin(['foo'])

array([ True,  True, False, False])